### ISSUE TITLE
looking for jdk in-> undefined

### ISSUE THREAD

**Issue by sauravpandit** [cesarvr/Ella#1]
I am getting the following issue when I am trying to install Ella in Windows 10
npm install ella

> npm WARN ella@1.5.1 No repository field.
> checking user jdk
> not found..
> looking in user folder for jdk
> looking for jdk in-> undefined/
> undefined/
> fs.js:909
>   return binding.readdir(pathModule._makeLong(path), options.encoding);
>                  ^
> 
> Error: ENOENT: no such file or directory, scandir 'F:\Node\nodeschool\html-pdf\node_modules\.staging\ella-40669603\undefined'
>     at Object.fs.readdirSync (fs.js:909:18)
>     at Object._search [as search] (F:\Node\nodeschool\html-pdf\node_modules\.staging\ella-40669603\node_modules\file-tools\file-tools.js:77:20)
>     at search_jdk (F:\Node\nodeschool\html-pdf\node_modules\.staging\ella-40669603\scripts\install.js:29:23)
>     at Array.look_user_folder (F:\Node\nodeschool\html-pdf\node_modules\.staging\ella-40669603\scripts\install.js:91:12)
>     at install (F:\Node\nodeschool\html-pdf\node_modules\.staging\ella-40669603\scripts\install.js:123:21)
>     at Object.<anonymous> (F:\Node\nodeschool\html-pdf\node_modules\.staging\ella-40669603\scripts\install.js:128:1)
>     at Module._compile (module.js:569:30)
>     at Object.Module._extensions..js (module.js:580:10)
>     at Module.load (module.js:503:32)
>     at tryModuleLoad (module.js:466:12)

I have already set JAVA_HOME environment variable.
It will be great if anyone help me on this.

**Comment by ja8an** [comment]
hey, did you get any answers?
